global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # System metrics
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']  # MySQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']  # PostgreSQL metrics