global:
  scrape_interval: 15s

scrape:configs:  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']  # PostgreSQL metrics

  - job_name: 'mysql'
    static_configs:
      - targets: ['postgres_exporter:9187']  # MySQL metrics
 