apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-deployment
  labels:
    app: simple-webapp
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - name: simple-webapp-container
        image: simple-webapp:latest # Or minikube/simple-webapp:latest if you loaded it into Minikube
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi