global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']