name: MySQL CI/CD Pipeline

on:
  push:

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database-lab

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p${{ secrets.MYSQL_ROOT_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysql -h127.0.0.1 -uroot -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "SELECT 1;" &> /dev/null; then
              echo "MySQL is ready!"
              exit 0
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL did not start in time"
          exit 1

      - name: Run SQL Init Scripts
        run: |
          mysql -h127.0.0.1 -uroot -prootpassword demo_db < init-scripts/01-create-table.sql
          mysql -h127.0.0.1 -uroot -prootpassword demo_db < init-scripts/02-seed-data.sql

      - name: Verify Database & Data
        run: |
          mysql -h127.0.0.1 -uroot -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" ${{ secrets.MYSQL_DATABASE }} < init-scripts/01-create-table.sql
          mysql -h127.0.0.1 -u"${{ secrets.MYSQL_USER }}" -p"${{ secrets.MYSQL_PASSWORD }}" ${{ secrets.MYSQL_DATABASE }} < init-scripts/02-seed-data.sql
