name: Node.js Docker CI

on:
  push:
    branches: [ "none" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push the image
        run: |
          echo "${{ secrets.GH_PAT }}" docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main:latest .

      - name: Push docker image
        run: |
            docker push .



        

  
        

          
        
  
