name: Node.js Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push the image
        run: |
          docker login --username burimsh --password-stdin ${{ secrets.GH_PAT }} ghcr.io






        

  
        

          
        
  
