name: Build node-js

on: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup node-version
        uses: action/setup-node@v3
        with:
          node-version: '16'

          
        
  
